<?xml version="1.0" encoding="utf-8"?><Database Name="Crocodylius" Class="DataCrocodylusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GERENCIA-VAIO;Initial Catalog=Crocodylius;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="CrocodyliusConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Proveedor" Member="Proveedor">
    <Type Name="Proveedor">
      <Column Name="ProveedorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InmodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NomProv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nota" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telf" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PagWeb" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CuentaContID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AnticipCuentaContID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GastoCuentaContID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo_Producto" Member="Tipo_Producto">
    <Type Name="Tipo_Producto">
      <Column Name="TipoProdID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InmodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NomTipoProd" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="ProductoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InmodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ImagenID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TipoProdID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProveedorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodFabrica" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NomProd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UnidMedida" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="StockMax" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockMin" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PedidMin" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Peso" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Marca" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CodBarra" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModifPrec" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CuentaContCompraID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CuentaContVentaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CuentaContCostoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Producto_KardexProd" Member="KardexProd" ThisKey="ProductoID" OtherKey="ProductoID" Type="KardexProd" />
    </Type>
  </Table>
  <Table Name="dbo.Almacen" Member="Almacen">
    <Type Name="Almacen">
      <Column Name="AlmacenID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InmodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UbicacionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NomAlmacen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NomEncAlmacen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Almacen_KardexProd" Member="KardexProd" ThisKey="AlmacenID" OtherKey="AlmacenID" Type="KardexProd" />
    </Type>
  </Table>
  <Table Name="dbo.KardexProd" Member="KardexProd">
    <Type Name="KardexProd">
      <Column Name="KardexProdID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AlmacenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="NroNota" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Referencia" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Entrada" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Salida" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockAlm" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockEmp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PUnitario" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Almacen_KardexProd" Member="Almacen" ThisKey="AlmacenID" OtherKey="AlmacenID" Type="Almacen" IsForeignKey="true" />
      <Association Name="Producto_KardexProd" Member="Producto" ThisKey="ProductoID" OtherKey="ProductoID" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cuenta_Contable" Member="Cuenta_Contable">
    <Type Name="Cuenta_Contable">
      <Column Name="CuentaContID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodCuenta" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PadreCuenta" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NomCuenta" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TipoCuenta" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Debe" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Haber" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Borrar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.BuscakardexProd" Method="BuscakardexProd">
    <Parameter Name="ProductoID" Parameter="productoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fechaini" Parameter="fechaini" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Fechafin" Parameter="fechafin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AlmacenID" Parameter="almacenID" Type="System.Int32" DbType="Int" />
    <ElementType Name="BuscakardexProdResult">
      <Column Name="KardexProdID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AlmacenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="NroNota" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Referencia" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Entrada" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Salida" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockAlm" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockEmp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PUnitario" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BuscarNombreCuenta" Method="BuscarNombreCuenta">
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" />
    <ElementType Name="BuscarNombreCuentaResult">
      <Column Name="NomCuenta" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>