#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Crocodylius")]
	public partial class DataCrocodylusDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertProveedor(Proveedor instance);
    partial void UpdateProveedor(Proveedor instance);
    partial void DeleteProveedor(Proveedor instance);
    partial void InsertTipo_Producto(Tipo_Producto instance);
    partial void UpdateTipo_Producto(Tipo_Producto instance);
    partial void DeleteTipo_Producto(Tipo_Producto instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertAlmacen(Almacen instance);
    partial void UpdateAlmacen(Almacen instance);
    partial void DeleteAlmacen(Almacen instance);
    partial void InsertKardexProd(KardexProd instance);
    partial void UpdateKardexProd(KardexProd instance);
    partial void DeleteKardexProd(KardexProd instance);
    partial void InsertCuenta_Contable(Cuenta_Contable instance);
    partial void UpdateCuenta_Contable(Cuenta_Contable instance);
    partial void DeleteCuenta_Contable(Cuenta_Contable instance);
    #endregion
		
		public DataCrocodylusDataContext() : 
				base(global::Datos.Properties.Settings.Default.CrocodyliusConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataCrocodylusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataCrocodylusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataCrocodylusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataCrocodylusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Proveedor> Proveedor
		{
			get
			{
				return this.GetTable<Proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Producto> Tipo_Producto
		{
			get
			{
				return this.GetTable<Tipo_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Almacen> Almacen
		{
			get
			{
				return this.GetTable<Almacen>();
			}
		}
		
		public System.Data.Linq.Table<KardexProd> KardexProd
		{
			get
			{
				return this.GetTable<KardexProd>();
			}
		}
		
		public System.Data.Linq.Table<Cuenta_Contable> Cuenta_Contable
		{
			get
			{
				return this.GetTable<Cuenta_Contable>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscakardexProd")]
		public ISingleResult<BuscakardexProdResult> BuscakardexProd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductoID", DbType="Int")] System.Nullable<int> productoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fechaini", DbType="DateTime")] System.Nullable<System.DateTime> fechaini, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fechafin", DbType="DateTime")] System.Nullable<System.DateTime> fechafin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlmacenID", DbType="Int")] System.Nullable<int> almacenID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productoID, fechaini, fechafin, almacenID);
			return ((ISingleResult<BuscakardexProdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarNombreCuenta")]
		public ISingleResult<BuscarNombreCuentaResult> BuscarNombreCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] System.Nullable<int> cuentaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaID);
			return ((ISingleResult<BuscarNombreCuentaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedor")]
	public partial class Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProveedorID;
		
		private long _InmodeID;
		
		private string _NomProv;
		
		private string _Nota;
		
		private string _Telf;
		
		private string _Fax;
		
		private string _PagWeb;
		
		private string _Correo;
		
		private long _CuentaContID;
		
		private long _AnticipCuentaContID;
		
		private long _GastoCuentaContID;
		
		private int _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProveedorIDChanging(int value);
    partial void OnProveedorIDChanged();
    partial void OnInmodeIDChanging(long value);
    partial void OnInmodeIDChanged();
    partial void OnNomProvChanging(string value);
    partial void OnNomProvChanged();
    partial void OnNotaChanging(string value);
    partial void OnNotaChanged();
    partial void OnTelfChanging(string value);
    partial void OnTelfChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnPagWebChanging(string value);
    partial void OnPagWebChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnCuentaContIDChanging(long value);
    partial void OnCuentaContIDChanged();
    partial void OnAnticipCuentaContIDChanging(long value);
    partial void OnAnticipCuentaContIDChanged();
    partial void OnGastoCuentaContIDChanging(long value);
    partial void OnGastoCuentaContIDChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Proveedor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProveedorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProveedorID
		{
			get
			{
				return this._ProveedorID;
			}
			set
			{
				if ((this._ProveedorID != value))
				{
					this.OnProveedorIDChanging(value);
					this.SendPropertyChanging();
					this._ProveedorID = value;
					this.SendPropertyChanged("ProveedorID");
					this.OnProveedorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InmodeID", DbType="BigInt NOT NULL")]
		public long InmodeID
		{
			get
			{
				return this._InmodeID;
			}
			set
			{
				if ((this._InmodeID != value))
				{
					this.OnInmodeIDChanging(value);
					this.SendPropertyChanging();
					this._InmodeID = value;
					this.SendPropertyChanged("InmodeID");
					this.OnInmodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomProv
		{
			get
			{
				return this._NomProv;
			}
			set
			{
				if ((this._NomProv != value))
				{
					this.OnNomProvChanging(value);
					this.SendPropertyChanging();
					this._NomProv = value;
					this.SendPropertyChanged("NomProv");
					this.OnNomProvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this.OnNotaChanging(value);
					this.SendPropertyChanging();
					this._Nota = value;
					this.SendPropertyChanged("Nota");
					this.OnNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telf", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Telf
		{
			get
			{
				return this._Telf;
			}
			set
			{
				if ((this._Telf != value))
				{
					this.OnTelfChanging(value);
					this.SendPropertyChanging();
					this._Telf = value;
					this.SendPropertyChanged("Telf");
					this.OnTelfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagWeb", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PagWeb
		{
			get
			{
				return this._PagWeb;
			}
			set
			{
				if ((this._PagWeb != value))
				{
					this.OnPagWebChanging(value);
					this.SendPropertyChanging();
					this._PagWeb = value;
					this.SendPropertyChanged("PagWeb");
					this.OnPagWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaContID", DbType="BigInt NOT NULL")]
		public long CuentaContID
		{
			get
			{
				return this._CuentaContID;
			}
			set
			{
				if ((this._CuentaContID != value))
				{
					this.OnCuentaContIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaContID = value;
					this.SendPropertyChanged("CuentaContID");
					this.OnCuentaContIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnticipCuentaContID", DbType="BigInt NOT NULL")]
		public long AnticipCuentaContID
		{
			get
			{
				return this._AnticipCuentaContID;
			}
			set
			{
				if ((this._AnticipCuentaContID != value))
				{
					this.OnAnticipCuentaContIDChanging(value);
					this.SendPropertyChanging();
					this._AnticipCuentaContID = value;
					this.SendPropertyChanged("AnticipCuentaContID");
					this.OnAnticipCuentaContIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GastoCuentaContID", DbType="BigInt NOT NULL")]
		public long GastoCuentaContID
		{
			get
			{
				return this._GastoCuentaContID;
			}
			set
			{
				if ((this._GastoCuentaContID != value))
				{
					this.OnGastoCuentaContIDChanging(value);
					this.SendPropertyChanging();
					this._GastoCuentaContID = value;
					this.SendPropertyChanged("GastoCuentaContID");
					this.OnGastoCuentaContIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Producto")]
	public partial class Tipo_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TipoProdID;
		
		private long _InmodeID;
		
		private string _NomTipoProd;
		
		private int _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipoProdIDChanging(int value);
    partial void OnTipoProdIDChanged();
    partial void OnInmodeIDChanging(long value);
    partial void OnInmodeIDChanged();
    partial void OnNomTipoProdChanging(string value);
    partial void OnNomTipoProdChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Tipo_Producto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProdID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TipoProdID
		{
			get
			{
				return this._TipoProdID;
			}
			set
			{
				if ((this._TipoProdID != value))
				{
					this.OnTipoProdIDChanging(value);
					this.SendPropertyChanging();
					this._TipoProdID = value;
					this.SendPropertyChanged("TipoProdID");
					this.OnTipoProdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InmodeID", DbType="BigInt NOT NULL")]
		public long InmodeID
		{
			get
			{
				return this._InmodeID;
			}
			set
			{
				if ((this._InmodeID != value))
				{
					this.OnInmodeIDChanging(value);
					this.SendPropertyChanging();
					this._InmodeID = value;
					this.SendPropertyChanged("InmodeID");
					this.OnInmodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomTipoProd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomTipoProd
		{
			get
			{
				return this._NomTipoProd;
			}
			set
			{
				if ((this._NomTipoProd != value))
				{
					this.OnNomTipoProdChanging(value);
					this.SendPropertyChanging();
					this._NomTipoProd = value;
					this.SendPropertyChanged("NomTipoProd");
					this.OnNomTipoProdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoID;
		
		private long _InmodeID;
		
		private long _ImagenID;
		
		private int _TipoProdID;
		
		private int _ProveedorID;
		
		private string _CodFabrica;
		
		private string _NomProd;
		
		private string _Descripcion;
		
		private string _UnidMedida;
		
		private string _Moneda;
		
		private decimal _StockMax;
		
		private decimal _StockMin;
		
		private decimal _PedidMin;
		
		private string _Peso;
		
		private string _Marca;
		
		private string _CodBarra;
		
		private int _ModifPrec;
		
		private long _CuentaContCompraID;
		
		private int _CuentaContVentaID;
		
		private int _CuentaContCostoID;
		
		private int _Estado;
		
		private EntitySet<KardexProd> _KardexProd;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIDChanging(int value);
    partial void OnProductoIDChanged();
    partial void OnInmodeIDChanging(long value);
    partial void OnInmodeIDChanged();
    partial void OnImagenIDChanging(long value);
    partial void OnImagenIDChanged();
    partial void OnTipoProdIDChanging(int value);
    partial void OnTipoProdIDChanged();
    partial void OnProveedorIDChanging(int value);
    partial void OnProveedorIDChanged();
    partial void OnCodFabricaChanging(string value);
    partial void OnCodFabricaChanged();
    partial void OnNomProdChanging(string value);
    partial void OnNomProdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnUnidMedidaChanging(string value);
    partial void OnUnidMedidaChanged();
    partial void OnMonedaChanging(string value);
    partial void OnMonedaChanged();
    partial void OnStockMaxChanging(decimal value);
    partial void OnStockMaxChanged();
    partial void OnStockMinChanging(decimal value);
    partial void OnStockMinChanged();
    partial void OnPedidMinChanging(decimal value);
    partial void OnPedidMinChanged();
    partial void OnPesoChanging(string value);
    partial void OnPesoChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnCodBarraChanging(string value);
    partial void OnCodBarraChanged();
    partial void OnModifPrecChanging(int value);
    partial void OnModifPrecChanged();
    partial void OnCuentaContCompraIDChanging(long value);
    partial void OnCuentaContCompraIDChanged();
    partial void OnCuentaContVentaIDChanging(int value);
    partial void OnCuentaContVentaIDChanged();
    partial void OnCuentaContCostoIDChanging(int value);
    partial void OnCuentaContCostoIDChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Producto()
		{
			this._KardexProd = new EntitySet<KardexProd>(new Action<KardexProd>(this.attach_KardexProd), new Action<KardexProd>(this.detach_KardexProd));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoID = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InmodeID", DbType="BigInt NOT NULL")]
		public long InmodeID
		{
			get
			{
				return this._InmodeID;
			}
			set
			{
				if ((this._InmodeID != value))
				{
					this.OnInmodeIDChanging(value);
					this.SendPropertyChanging();
					this._InmodeID = value;
					this.SendPropertyChanged("InmodeID");
					this.OnInmodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenID", DbType="BigInt NOT NULL")]
		public long ImagenID
		{
			get
			{
				return this._ImagenID;
			}
			set
			{
				if ((this._ImagenID != value))
				{
					this.OnImagenIDChanging(value);
					this.SendPropertyChanging();
					this._ImagenID = value;
					this.SendPropertyChanged("ImagenID");
					this.OnImagenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProdID", DbType="Int NOT NULL")]
		public int TipoProdID
		{
			get
			{
				return this._TipoProdID;
			}
			set
			{
				if ((this._TipoProdID != value))
				{
					this.OnTipoProdIDChanging(value);
					this.SendPropertyChanging();
					this._TipoProdID = value;
					this.SendPropertyChanged("TipoProdID");
					this.OnTipoProdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProveedorID", DbType="Int NOT NULL")]
		public int ProveedorID
		{
			get
			{
				return this._ProveedorID;
			}
			set
			{
				if ((this._ProveedorID != value))
				{
					this.OnProveedorIDChanging(value);
					this.SendPropertyChanging();
					this._ProveedorID = value;
					this.SendPropertyChanged("ProveedorID");
					this.OnProveedorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodFabrica", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodFabrica
		{
			get
			{
				return this._CodFabrica;
			}
			set
			{
				if ((this._CodFabrica != value))
				{
					this.OnCodFabricaChanging(value);
					this.SendPropertyChanging();
					this._CodFabrica = value;
					this.SendPropertyChanged("CodFabrica");
					this.OnCodFabricaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomProd
		{
			get
			{
				return this._NomProd;
			}
			set
			{
				if ((this._NomProd != value))
				{
					this.OnNomProdChanging(value);
					this.SendPropertyChanging();
					this._NomProd = value;
					this.SendPropertyChanged("NomProd");
					this.OnNomProdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidMedida", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UnidMedida
		{
			get
			{
				return this._UnidMedida;
			}
			set
			{
				if ((this._UnidMedida != value))
				{
					this.OnUnidMedidaChanging(value);
					this.SendPropertyChanging();
					this._UnidMedida = value;
					this.SendPropertyChanged("UnidMedida");
					this.OnUnidMedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this.OnMonedaChanging(value);
					this.SendPropertyChanging();
					this._Moneda = value;
					this.SendPropertyChanged("Moneda");
					this.OnMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMax", DbType="Money NOT NULL")]
		public decimal StockMax
		{
			get
			{
				return this._StockMax;
			}
			set
			{
				if ((this._StockMax != value))
				{
					this.OnStockMaxChanging(value);
					this.SendPropertyChanging();
					this._StockMax = value;
					this.SendPropertyChanged("StockMax");
					this.OnStockMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMin", DbType="Money NOT NULL")]
		public decimal StockMin
		{
			get
			{
				return this._StockMin;
			}
			set
			{
				if ((this._StockMin != value))
				{
					this.OnStockMinChanging(value);
					this.SendPropertyChanging();
					this._StockMin = value;
					this.SendPropertyChanged("StockMin");
					this.OnStockMinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PedidMin", DbType="Money NOT NULL")]
		public decimal PedidMin
		{
			get
			{
				return this._PedidMin;
			}
			set
			{
				if ((this._PedidMin != value))
				{
					this.OnPedidMinChanging(value);
					this.SendPropertyChanging();
					this._PedidMin = value;
					this.SendPropertyChanged("PedidMin");
					this.OnPedidMinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this.OnPesoChanging(value);
					this.SendPropertyChanging();
					this._Peso = value;
					this.SendPropertyChanged("Peso");
					this.OnPesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodBarra", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CodBarra
		{
			get
			{
				return this._CodBarra;
			}
			set
			{
				if ((this._CodBarra != value))
				{
					this.OnCodBarraChanging(value);
					this.SendPropertyChanging();
					this._CodBarra = value;
					this.SendPropertyChanged("CodBarra");
					this.OnCodBarraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifPrec", DbType="Int NOT NULL")]
		public int ModifPrec
		{
			get
			{
				return this._ModifPrec;
			}
			set
			{
				if ((this._ModifPrec != value))
				{
					this.OnModifPrecChanging(value);
					this.SendPropertyChanging();
					this._ModifPrec = value;
					this.SendPropertyChanged("ModifPrec");
					this.OnModifPrecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaContCompraID", DbType="BigInt NOT NULL")]
		public long CuentaContCompraID
		{
			get
			{
				return this._CuentaContCompraID;
			}
			set
			{
				if ((this._CuentaContCompraID != value))
				{
					this.OnCuentaContCompraIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaContCompraID = value;
					this.SendPropertyChanged("CuentaContCompraID");
					this.OnCuentaContCompraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaContVentaID", DbType="Int NOT NULL")]
		public int CuentaContVentaID
		{
			get
			{
				return this._CuentaContVentaID;
			}
			set
			{
				if ((this._CuentaContVentaID != value))
				{
					this.OnCuentaContVentaIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaContVentaID = value;
					this.SendPropertyChanged("CuentaContVentaID");
					this.OnCuentaContVentaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaContCostoID", DbType="Int NOT NULL")]
		public int CuentaContCostoID
		{
			get
			{
				return this._CuentaContCostoID;
			}
			set
			{
				if ((this._CuentaContCostoID != value))
				{
					this.OnCuentaContCostoIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaContCostoID = value;
					this.SendPropertyChanged("CuentaContCostoID");
					this.OnCuentaContCostoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_KardexProd", Storage="_KardexProd", ThisKey="ProductoID", OtherKey="ProductoID")]
		public EntitySet<KardexProd> KardexProd
		{
			get
			{
				return this._KardexProd;
			}
			set
			{
				this._KardexProd.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KardexProd(KardexProd entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_KardexProd(KardexProd entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Almacen")]
	public partial class Almacen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AlmacenID;
		
		private long _InmodeID;
		
		private long _UbicacionID;
		
		private string _NomAlmacen;
		
		private string _NomEncAlmacen;
		
		private int _Estado;
		
		private EntitySet<KardexProd> _KardexProd;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAlmacenIDChanging(int value);
    partial void OnAlmacenIDChanged();
    partial void OnInmodeIDChanging(long value);
    partial void OnInmodeIDChanged();
    partial void OnUbicacionIDChanging(long value);
    partial void OnUbicacionIDChanged();
    partial void OnNomAlmacenChanging(string value);
    partial void OnNomAlmacenChanged();
    partial void OnNomEncAlmacenChanging(string value);
    partial void OnNomEncAlmacenChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Almacen()
		{
			this._KardexProd = new EntitySet<KardexProd>(new Action<KardexProd>(this.attach_KardexProd), new Action<KardexProd>(this.detach_KardexProd));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlmacenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AlmacenID
		{
			get
			{
				return this._AlmacenID;
			}
			set
			{
				if ((this._AlmacenID != value))
				{
					this.OnAlmacenIDChanging(value);
					this.SendPropertyChanging();
					this._AlmacenID = value;
					this.SendPropertyChanged("AlmacenID");
					this.OnAlmacenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InmodeID", DbType="BigInt NOT NULL")]
		public long InmodeID
		{
			get
			{
				return this._InmodeID;
			}
			set
			{
				if ((this._InmodeID != value))
				{
					this.OnInmodeIDChanging(value);
					this.SendPropertyChanging();
					this._InmodeID = value;
					this.SendPropertyChanged("InmodeID");
					this.OnInmodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UbicacionID", DbType="BigInt NOT NULL")]
		public long UbicacionID
		{
			get
			{
				return this._UbicacionID;
			}
			set
			{
				if ((this._UbicacionID != value))
				{
					this.OnUbicacionIDChanging(value);
					this.SendPropertyChanging();
					this._UbicacionID = value;
					this.SendPropertyChanged("UbicacionID");
					this.OnUbicacionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomAlmacen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomAlmacen
		{
			get
			{
				return this._NomAlmacen;
			}
			set
			{
				if ((this._NomAlmacen != value))
				{
					this.OnNomAlmacenChanging(value);
					this.SendPropertyChanging();
					this._NomAlmacen = value;
					this.SendPropertyChanged("NomAlmacen");
					this.OnNomAlmacenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomEncAlmacen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomEncAlmacen
		{
			get
			{
				return this._NomEncAlmacen;
			}
			set
			{
				if ((this._NomEncAlmacen != value))
				{
					this.OnNomEncAlmacenChanging(value);
					this.SendPropertyChanging();
					this._NomEncAlmacen = value;
					this.SendPropertyChanged("NomEncAlmacen");
					this.OnNomEncAlmacenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Almacen_KardexProd", Storage="_KardexProd", ThisKey="AlmacenID", OtherKey="AlmacenID")]
		public EntitySet<KardexProd> KardexProd
		{
			get
			{
				return this._KardexProd;
			}
			set
			{
				this._KardexProd.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KardexProd(KardexProd entity)
		{
			this.SendPropertyChanging();
			entity.Almacen = this;
		}
		
		private void detach_KardexProd(KardexProd entity)
		{
			this.SendPropertyChanging();
			entity.Almacen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KardexProd")]
	public partial class KardexProd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _KardexProdID;
		
		private int _AlmacenID;
		
		private int _ProductoID;
		
		private System.DateTime _Fecha;
		
		private string _NroNota;
		
		private string _Referencia;
		
		private decimal _Entrada;
		
		private decimal _Salida;
		
		private decimal _StockAlm;
		
		private decimal _StockEmp;
		
		private decimal _PUnitario;
		
		private string _Detalle;
		
		private int _Estado;
		
		private EntityRef<Almacen> _Almacen;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKardexProdIDChanging(long value);
    partial void OnKardexProdIDChanged();
    partial void OnAlmacenIDChanging(int value);
    partial void OnAlmacenIDChanged();
    partial void OnProductoIDChanging(int value);
    partial void OnProductoIDChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnNroNotaChanging(string value);
    partial void OnNroNotaChanged();
    partial void OnReferenciaChanging(string value);
    partial void OnReferenciaChanged();
    partial void OnEntradaChanging(decimal value);
    partial void OnEntradaChanged();
    partial void OnSalidaChanging(decimal value);
    partial void OnSalidaChanged();
    partial void OnStockAlmChanging(decimal value);
    partial void OnStockAlmChanged();
    partial void OnStockEmpChanging(decimal value);
    partial void OnStockEmpChanged();
    partial void OnPUnitarioChanging(decimal value);
    partial void OnPUnitarioChanged();
    partial void OnDetalleChanging(string value);
    partial void OnDetalleChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public KardexProd()
		{
			this._Almacen = default(EntityRef<Almacen>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KardexProdID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long KardexProdID
		{
			get
			{
				return this._KardexProdID;
			}
			set
			{
				if ((this._KardexProdID != value))
				{
					this.OnKardexProdIDChanging(value);
					this.SendPropertyChanging();
					this._KardexProdID = value;
					this.SendPropertyChanged("KardexProdID");
					this.OnKardexProdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlmacenID", DbType="Int NOT NULL")]
		public int AlmacenID
		{
			get
			{
				return this._AlmacenID;
			}
			set
			{
				if ((this._AlmacenID != value))
				{
					if (this._Almacen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAlmacenIDChanging(value);
					this.SendPropertyChanging();
					this._AlmacenID = value;
					this.SendPropertyChanged("AlmacenID");
					this.OnAlmacenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoID", DbType="Int NOT NULL")]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoID = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroNota", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NroNota
		{
			get
			{
				return this._NroNota;
			}
			set
			{
				if ((this._NroNota != value))
				{
					this.OnNroNotaChanging(value);
					this.SendPropertyChanging();
					this._NroNota = value;
					this.SendPropertyChanged("NroNota");
					this.OnNroNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Referencia
		{
			get
			{
				return this._Referencia;
			}
			set
			{
				if ((this._Referencia != value))
				{
					this.OnReferenciaChanging(value);
					this.SendPropertyChanging();
					this._Referencia = value;
					this.SendPropertyChanged("Referencia");
					this.OnReferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="Money NOT NULL")]
		public decimal Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this.OnEntradaChanging(value);
					this.SendPropertyChanging();
					this._Entrada = value;
					this.SendPropertyChanged("Entrada");
					this.OnEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salida", DbType="Money NOT NULL")]
		public decimal Salida
		{
			get
			{
				return this._Salida;
			}
			set
			{
				if ((this._Salida != value))
				{
					this.OnSalidaChanging(value);
					this.SendPropertyChanging();
					this._Salida = value;
					this.SendPropertyChanged("Salida");
					this.OnSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockAlm", DbType="Money NOT NULL")]
		public decimal StockAlm
		{
			get
			{
				return this._StockAlm;
			}
			set
			{
				if ((this._StockAlm != value))
				{
					this.OnStockAlmChanging(value);
					this.SendPropertyChanging();
					this._StockAlm = value;
					this.SendPropertyChanged("StockAlm");
					this.OnStockAlmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockEmp", DbType="Money NOT NULL")]
		public decimal StockEmp
		{
			get
			{
				return this._StockEmp;
			}
			set
			{
				if ((this._StockEmp != value))
				{
					this.OnStockEmpChanging(value);
					this.SendPropertyChanging();
					this._StockEmp = value;
					this.SendPropertyChanged("StockEmp");
					this.OnStockEmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUnitario", DbType="Money NOT NULL")]
		public decimal PUnitario
		{
			get
			{
				return this._PUnitario;
			}
			set
			{
				if ((this._PUnitario != value))
				{
					this.OnPUnitarioChanging(value);
					this.SendPropertyChanging();
					this._PUnitario = value;
					this.SendPropertyChanged("PUnitario");
					this.OnPUnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this.OnDetalleChanging(value);
					this.SendPropertyChanging();
					this._Detalle = value;
					this.SendPropertyChanged("Detalle");
					this.OnDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Almacen_KardexProd", Storage="_Almacen", ThisKey="AlmacenID", OtherKey="AlmacenID", IsForeignKey=true)]
		public Almacen Almacen
		{
			get
			{
				return this._Almacen.Entity;
			}
			set
			{
				Almacen previousValue = this._Almacen.Entity;
				if (((previousValue != value) 
							|| (this._Almacen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Almacen.Entity = null;
						previousValue.KardexProd.Remove(this);
					}
					this._Almacen.Entity = value;
					if ((value != null))
					{
						value.KardexProd.Add(this);
						this._AlmacenID = value.AlmacenID;
					}
					else
					{
						this._AlmacenID = default(int);
					}
					this.SendPropertyChanged("Almacen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_KardexProd", Storage="_Producto", ThisKey="ProductoID", OtherKey="ProductoID", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.KardexProd.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.KardexProd.Add(this);
						this._ProductoID = value.ProductoID;
					}
					else
					{
						this._ProductoID = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cuenta_Contable")]
	public partial class Cuenta_Contable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CuentaContID;
		
		private string _CodCuenta;
		
		private string _PadreCuenta;
		
		private string _NomCuenta;
		
		private string _Detalle;
		
		private string _Moneda;
		
		private string _TipoCuenta;
		
		private decimal _Debe;
		
		private decimal _Haber;
		
		private int _Borrar;
		
		private int _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCuentaContIDChanging(int value);
    partial void OnCuentaContIDChanged();
    partial void OnCodCuentaChanging(string value);
    partial void OnCodCuentaChanged();
    partial void OnPadreCuentaChanging(string value);
    partial void OnPadreCuentaChanged();
    partial void OnNomCuentaChanging(string value);
    partial void OnNomCuentaChanged();
    partial void OnDetalleChanging(string value);
    partial void OnDetalleChanged();
    partial void OnMonedaChanging(string value);
    partial void OnMonedaChanged();
    partial void OnTipoCuentaChanging(string value);
    partial void OnTipoCuentaChanged();
    partial void OnDebeChanging(decimal value);
    partial void OnDebeChanged();
    partial void OnHaberChanging(decimal value);
    partial void OnHaberChanged();
    partial void OnBorrarChanging(int value);
    partial void OnBorrarChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Cuenta_Contable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaContID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CuentaContID
		{
			get
			{
				return this._CuentaContID;
			}
			set
			{
				if ((this._CuentaContID != value))
				{
					this.OnCuentaContIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaContID = value;
					this.SendPropertyChanged("CuentaContID");
					this.OnCuentaContIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PadreCuenta", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PadreCuenta
		{
			get
			{
				return this._PadreCuenta;
			}
			set
			{
				if ((this._PadreCuenta != value))
				{
					this.OnPadreCuentaChanging(value);
					this.SendPropertyChanging();
					this._PadreCuenta = value;
					this.SendPropertyChanged("PadreCuenta");
					this.OnPadreCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomCuenta", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomCuenta
		{
			get
			{
				return this._NomCuenta;
			}
			set
			{
				if ((this._NomCuenta != value))
				{
					this.OnNomCuentaChanging(value);
					this.SendPropertyChanging();
					this._NomCuenta = value;
					this.SendPropertyChanged("NomCuenta");
					this.OnNomCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this.OnDetalleChanging(value);
					this.SendPropertyChanging();
					this._Detalle = value;
					this.SendPropertyChanged("Detalle");
					this.OnDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this.OnMonedaChanging(value);
					this.SendPropertyChanging();
					this._Moneda = value;
					this.SendPropertyChanged("Moneda");
					this.OnMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuenta", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TipoCuenta
		{
			get
			{
				return this._TipoCuenta;
			}
			set
			{
				if ((this._TipoCuenta != value))
				{
					this.OnTipoCuentaChanging(value);
					this.SendPropertyChanging();
					this._TipoCuenta = value;
					this.SendPropertyChanged("TipoCuenta");
					this.OnTipoCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debe", DbType="Money NOT NULL")]
		public decimal Debe
		{
			get
			{
				return this._Debe;
			}
			set
			{
				if ((this._Debe != value))
				{
					this.OnDebeChanging(value);
					this.SendPropertyChanging();
					this._Debe = value;
					this.SendPropertyChanged("Debe");
					this.OnDebeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haber", DbType="Money NOT NULL")]
		public decimal Haber
		{
			get
			{
				return this._Haber;
			}
			set
			{
				if ((this._Haber != value))
				{
					this.OnHaberChanging(value);
					this.SendPropertyChanging();
					this._Haber = value;
					this.SendPropertyChanged("Haber");
					this.OnHaberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrar", DbType="Int NOT NULL")]
		public int Borrar
		{
			get
			{
				return this._Borrar;
			}
			set
			{
				if ((this._Borrar != value))
				{
					this.OnBorrarChanging(value);
					this.SendPropertyChanging();
					this._Borrar = value;
					this.SendPropertyChanged("Borrar");
					this.OnBorrarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class BuscakardexProdResult
	{
		
		private long _KardexProdID;
		
		private int _AlmacenID;
		
		private int _ProductoID;
		
		private System.DateTime _Fecha;
		
		private string _NroNota;
		
		private string _Referencia;
		
		private decimal _Entrada;
		
		private decimal _Salida;
		
		private decimal _StockAlm;
		
		private decimal _StockEmp;
		
		private decimal _PUnitario;
		
		private string _Detalle;
		
		private int _Estado;
		
		public BuscakardexProdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KardexProdID", DbType="BigInt NOT NULL")]
		public long KardexProdID
		{
			get
			{
				return this._KardexProdID;
			}
			set
			{
				if ((this._KardexProdID != value))
				{
					this._KardexProdID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlmacenID", DbType="Int NOT NULL")]
		public int AlmacenID
		{
			get
			{
				return this._AlmacenID;
			}
			set
			{
				if ((this._AlmacenID != value))
				{
					this._AlmacenID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoID", DbType="Int NOT NULL")]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					this._ProductoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroNota", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NroNota
		{
			get
			{
				return this._NroNota;
			}
			set
			{
				if ((this._NroNota != value))
				{
					this._NroNota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Referencia
		{
			get
			{
				return this._Referencia;
			}
			set
			{
				if ((this._Referencia != value))
				{
					this._Referencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="Money NOT NULL")]
		public decimal Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this._Entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salida", DbType="Money NOT NULL")]
		public decimal Salida
		{
			get
			{
				return this._Salida;
			}
			set
			{
				if ((this._Salida != value))
				{
					this._Salida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockAlm", DbType="Money NOT NULL")]
		public decimal StockAlm
		{
			get
			{
				return this._StockAlm;
			}
			set
			{
				if ((this._StockAlm != value))
				{
					this._StockAlm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockEmp", DbType="Money NOT NULL")]
		public decimal StockEmp
		{
			get
			{
				return this._StockEmp;
			}
			set
			{
				if ((this._StockEmp != value))
				{
					this._StockEmp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUnitario", DbType="Money NOT NULL")]
		public decimal PUnitario
		{
			get
			{
				return this._PUnitario;
			}
			set
			{
				if ((this._PUnitario != value))
				{
					this._PUnitario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this._Detalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class BuscarNombreCuentaResult
	{
		
		private string _NomCuenta;
		
		public BuscarNombreCuentaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomCuenta", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomCuenta
		{
			get
			{
				return this._NomCuenta;
			}
			set
			{
				if ((this._NomCuenta != value))
				{
					this._NomCuenta = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
