//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRTechnology1._0 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ConfigGRTech : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigGRTech defaultInstance = ((ConfigGRTech)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigGRTech())));
        
        public static ConfigGRTech Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MEDIA CARTA")]
        public string Formato_Impr_Nota_Venta {
            get {
                return ((string)(this["Formato_Impr_Nota_Venta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Impr_Aut_Nota_Venta {
            get {
                return ((bool)(this["Impr_Aut_Nota_Venta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Proyectos\\ACTUALIZADOR\\Actualizador\\Actualizador\\bin\\Debug\\Actualizador.exe")]
        public string Ubicación_Sistem_Actualizador {
            get {
                return ((string)(this["Ubicación_Sistem_Actualizador"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Display_COM {
            get {
                return ((string)(this["Display_COM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Display_BaudRate {
            get {
                return ((string)(this["Display_BaudRate"]));
            }
        }
    }
}
